# Database Connection using Environment Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Relationship management
spring.jackson.serialization.fail-on-empty-beans=false

# Server Port (assigned dynamically by Render/cloud host, defaults to 8080 locally)
server.port=${PORT:8080}